#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make 3D mesh in slab of cells.

cd airfoil_snappyHexMesh/
blockMesh > output/1-blockMesh.log 2>&1
snappyHexMesh -overwrite > output/3-snappyHexMesh.log 2>&1
echo "starting pimple"



# Copy the mesh from the steady state case and map the results to a
# transient case, then solve transient.
cd ../airfoil_pimpleFoam
extrudeMesh > output/1-extrudeMesh.log 2>&1
mkdir 0
rm -f 0/*
cp 0.org/* 0/
decomposePar > output/2-decomposePar.log 2>&1
#mpirun -np 4 pimpleFoam -parallel > output/3-pimpleFoam.log 2>&1
runParallel pimpleFoam
date 
echo "pimple finished"
runApplication reconstructPar
#rm -rf proc*
#---------------------------------------------------------------------
